mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('u/', include('users.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views as v

app_name = 'polls'
urlpatterns = [
    path('', v.IndexView.as_view(), name='index'),
    path('<int:pk>/', v.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', v.ResultsView.as_view(), name='results'),
    path('<int:q_id>/vote/', v.vote, name='vote'),
]

users/urls.py
from django.urls import path

from . import views as v

app_name = 'users'
urlpatterns = [
    path('signup/', v.signup, name='signup'),
    path('signin/', v.SignInView.as_view(), name='signin'),
    path('logout/', v.LogOutView.as_view(), name='logout'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('publication date')

    def is_recent(self):
        """ Is the question published in last 24 hours? """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    is_recent.admin_order_field = 'pub_date'
    is_recent.boolean = True
    is_recent.short_description = 'Is recent?'

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.text

users/models.py
from django.db import models
from django.contrib.auth.models import User

from polls.models import Choice


class MyUser(User):
    votes = models.ManyToManyField(Choice, 'users')

users/forms.py
from django.contrib.auth.forms import (UserCreationForm, AuthenticationForm)

from polls.utils import AuthFormMixin

from users.models import MyUser


class SignUpForm(AuthFormMixin, UserCreationForm):
    class Meta:
        model = MyUser
        fields = ('username', 'password1', 'password2')


class SignInForm(AuthFormMixin, AuthenticationForm):
    class Meta:
        model = MyUser

polls/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'most_recent'

    def get_queryset(self):
        """ Return the most recent 5 questions """
        return Question.objects.filter(
            pub_date__lte=timezone.now(),
            choice__text__isnull=False).distinct().order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    template_name = 'polls/detail.html'
    context_object_name = 'q'

    def get_queryset(self):
        """ Filter questions.
        Filter: exclude not yet published questions.
        Filter: exclude questions without choices.
        """
        return Question.objects.filter(pub_date__lte=timezone.now(),
                                       choice__text__isnull=False).distinct()


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    context_object_name = 'q'


@login_required
def vote(req, q_id):
    q = get_object_or_404(Question, pk=q_id)
    try:
        selected_choice = q.choice_set.get(pk=req.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        messages.add_message(req, messages.INFO, "You didn't select a choice")
        return redirect('polls:detail', q.id)

    selected_choice.votes += 1
    selected_choice.save()
    return redirect('polls:results', q.id)

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView

from .forms import SignUpForm, SignInForm


def signup(req):
    form = SignUpForm(req.POST or None)
    next = reverse_lazy('users:signin')
    to_render = render(req, 'users/signup.html', {'form': form, 'next': next})

    if req.method == 'POST':
        if not form.is_valid():
            return to_render

        form.save()

        return redirect(req.POST.get('next', next))

    return to_render


class SignInView(LoginView):
    template_name = 'users/signin.html'
    authentication_form = SignInForm


class LogOutView(LogoutView):
    next_page = reverse_lazy('users:signin')

polls/templates/polls/detail.html
{% extends 'wrapper.html' %}


{% block title %}Question #{{ q.id }}{% endblock %}

{% block header %}
  <h2><span class="teal-text text-darken-4">{{ q.text }}</span></h2>
{% endblock %}

{% block content %}
  {% for message in messages %}
    <script>M.toast({html: '{{ message }}'})</script>
  {% endfor %}

  <form action="{% url 'polls:vote' q.id %}" method="post">
    {% csrf_token %}
    {% for choice in q.choice_set.all %}
      <p class="vote-option-wrapper">
        <label>
          <input type="radio" name="choice" value="{{ choice.id }}"
          class="with-gap">
          <span class="vote-option">{{ choice.text }}</span>
        </label>
      </p>
    {% endfor %}
    <button class="btn btn-large waves-effect waves-light"
    type="submit" name="action">
      Vote
      <i class="material-icons right">send</i>
    </button>
    <a href="{% url 'polls:index' %}" 
    class="btn btn-large waves-effect waves-light">
      All polls
    </a>
  </form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'wrapper.html' %}


{% block title %}Polls{% endblock %}

{% block header %}
  <h2><span class="teal-text text-darken-4">Most recent polls</span></h2>
{% endblock %}

{% block content %}
  {% if most_recent %}
    {% for q in most_recent %}
      <div class="col s12 m6">
        <div class="card white">
          <div class="card-content teal-text text-darken-4">
            <span class="card-title">{{ q.text }}</span>
          </div>
          <div class="card-action teal darken-3">
            <a href="{% url 'polls:detail' q.id %}" class="white-text">
              Go to voting page
              <i class="material-icons right">chevron_right</i>
            </a>
          </div>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No polls are available.</p>
  {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'wrapper.html' %}


{% block title %}Voting results{% endblock %}

{% block header %}
  <h2><span class="teal-text text-darken-4">
    Results on question "{{ q.text }}"
  </span></h2>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="collection col s12 m6">
      {% for choice in q.choice_set.all %}
        <div class="collection-item">
          <div>
            {{ choice.text }}
            <div class="votes-count secondary-content">{{ choice.votes }}</div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

  <a href="{% url 'polls:index' %}" 
  class="btn btn-large waves-effect waves-light">
    All polls
  </a>
{% endblock %}

templates/wrapper.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
  rel="stylesheet">
  <link type="text/css" rel="stylesheet" 
  href="{% static 'css/materialize.css' %}"  media="screen,projection"/>
  <link rel="stylesheet" href="{% static 'css/polls/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">

  <title>{% block title %}
    `title` not overriden
  {% endblock %} - My Site</title>

  <script src="{% static 'js/materialize.js' %}"></script>
</head>
<body>

  <nav class="teal">
    <div class="nav-wrapper container">
      <a href="{% url 'polls:index' %}" class="brand-logo">Polls</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        {% if user.is_authenticated %}
          <li><a href="{% url 'polls:index' %}">{{ user.username }}</a></li>
          <li><a href="{% url 'users:logout' %}">Log Out</a></li>
        {% else %}
          <li><a href="{% url 'users:signup' %}">Sign Up</a></li>
          <li><a href="{% url 'users:signin' %}">Sign In</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="col s12 m9 l8">
        <div class="row">
          <header>
            {% block header %}`header` not overriden{% endblock %}
          </header>
        </div>

        <div class="row">
          <section class="content">
            {% block content %}
              `content` not overriden
            {% endblock %}
          </section>
        </div>
      </div>

      <div class="col s0 m3 l4">
        <div class="sidebar">
          The sidebar
        </div>
      </div>
    </div>
  </div>

</body>
</html>

users/templates/includes/users/auth_form.html
<form method="post">
  {% csrf_token %}

  {% for field in form %}
    <div class="input-field row">
      {{ field }}
      {{ field.label_tag }}
      {{ field.errors }}
    </div>
  {% endfor %}

  <input type="hidden" name="next" value="{{ next }}">

  <button type="submit" class="btn btn-large waves-effect waves-light">
    Submit
    <i class="material-icons right">chevron_right</i>
  </button>
</form>

users/templates/users/signin.html
{% extends 'wrapper.html' %}


{% block title %}Sign In{% endblock %}

{% block header %}
  <h2><span class="teal-text text-darken-4">
    Sign In
  </span></h2>
{% endblock %}

{% block content %}
  {% include 'includes/users/auth_form.html' %}
{% endblock %}

users/templates/users/signup.html
{% extends 'wrapper.html' %}


{% block title %}Sign Up{% endblock %}

{% block header %}
  <h2><span class="teal-text text-darken-4">
    Sign Up
  </span></h2>
{% endblock %}

{% block content %}
  {% include 'includes/users/auth_form.html' %}
{% endblock %}